Models/Context.cs
using CoreDepartmant.Models;
using Microsoft.EntityFrameworkCore;

namespace CoreDepartment.Models
{
	public class Context : DbContext
	{
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlServer("server=BARANPC\\SQLEXPRESS; database=CorePersonel; integrated security=true; TrustServerCertificate=true");
		}

		public DbSet<Department> departments { get; set; }
        public DbSet<Personel> personels { get; set; }
    }
}

Models/Department.cs
using CoreDepartment.Models;
using System.ComponentModel.DataAnnotations;

namespace CoreDepartmant.Models
{
	public class Department
	{
        [Key]
        public int ID { get; set; }
        public string departmentName { get; set; }

        public List<Personel> Personels { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace CoreDepartmant.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/Personel.cs
using CoreDepartmant.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreDepartment.Models
{
	public class Personel
	{
        [Key]
        public int personalID { get; set; }
		public string personalName { get; set; }
        public string personalSurname { get; set; }
        public string personalCity { get; set; }
        public Department depart { get; set; }
    }
}

Controllers/DepartController.cs
using Microsoft.AspNetCore.Mvc;
using CoreDepartment.Models;
using CoreDepartmant.Models;

namespace CoreDepartment.Controllers
{
	public class DepartController : Controller
	{
		Context c = new Context();
		public IActionResult Index()
		{
			var values = c.departments.ToList();
			return View(values);
		}
		[HttpGet]
		public IActionResult NewDepartment()
		{
			return View(); 
		}
		[HttpPost]
		public IActionResult NewDepartment(Department d)
		{
			c.departments.Add(d);
			c.SaveChanges();
			return RedirectToAction("Index");
		}
		public IActionResult DeleteDepartment(int id)
		{
			var dep=c.departments.Find(id);
			c.departments.Remove(dep);
			c.SaveChanges();
			return RedirectToAction("Index");
		}
		public IActionResult ReturnDepartment(int id)
		{
			var depart=c.departments.Find(id);
			return View("ReturnDepartment", depart);
		}
		public IActionResult UpdateDepartment(Department d)
		{
			var dep = c.departments.Find(d.ID);
			dep.departmentName = d.departmentName;
			c.SaveChanges();
			return RedirectToAction("Index");
		}
	}
}

Controllers/HomeController.cs
using CoreDepartmant.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CoreDepartmant.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/personelController.cs
using CoreDepartment.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreDepartment.Controllers
{
	public class personelController : Controller
	{
		Context c = new Context();
		public IActionResult Index()
		{
			var values = c.personels.ToList();
			return View(values);
		}
	}
}

Views/Depart/Index.cshtml
@using CoreDepartment.Models
@model List<Department>
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_TestLayout.cshtml";
}
<br />
<table class="table table-bordered">
	<tr>
		<th>ID</th>
		<th>Department</th>
		<th>Delete</th>
		<th>Update</th>
		<th>Details</th>
	</tr>
	@foreach(var x in Model)
	{
		<tr>
			<td>@x.ID</td>
			<td>@x.departmentName</td>
			<td><a href="/Depart/DeleteDepartment/@x.ID" class="btn btn-danger">DELETE</a></td>
			<td><a href="/Depart/ReturnDepartment/@x.ID" class="btn btn-success">UPDATE</a></td>
			<td><a href="#" class="btn btn-default" style="background-color:#FCE032">DETAILS</a></td>
		</tr>
	}
</table>
<a href="/depart/NewDepartment/" class="btn btn-primary">New Department</a>

Views/Depart/NewDepartment.cshtml
@model CoreDepartmant.Models.Department
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<form class="form-group" method="post">

	<b>Department Name</b>
	@Html.TextBoxFor(x => x.departmentName, new {@class="form-control"})
	<br />
	<button class="btn btn-info">Add Department</button>
</form>

Views/Depart/ReturnDepartment.cshtml
@model CoreDepartmant.Models.Department
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />

@using(Html.BeginForm("UpdateDepartment", "Depart",FormMethod.Post))
{
	<b>Department ID</b>
	@Html.TextBoxFor(x => x.ID, new { @class = "form-control" })
	<br />
	<b>Department Name</b>
	@Html.TextBoxFor(x => x.departmentName, new { @class = "form-control" })
	<br />
	<button class="btn btn-default" style="background-color:#ebdede; color:black">Update Department</button>
}

Views/Depart/_TestLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Personel/Index.cshtml
@using CoreDepartment.Models
@model List<Personel>
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_TestLayout.cshtml";
}
<br />
<table class="table table-bordered">
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Surname</th>
		<th>City</th>
		<th>Delete</th>
		<th>Update</th>
	</tr>
	@foreach (var x in Model)
	{
		<tr>
			<td>@x.personalID</td>
			<td>@x.personalName</td>
			<td>@x.personalSurname</td>
			<td>@x.personalCity</td>
			<td><a href="/Depart/DeleteDepartment/@x.personalID" class="btn btn-danger">DELETE</a></td>
			<td><a href="/Depart/ReturnDepartment/@x.personalID" class="btn btn-success">UPDATE</a></td>
		</tr>
	}
</table>
<a href="/depart/NewDepartment/" class="btn btn-primary">New Personel</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreDepartmant</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoreDepartmant.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreDepartmant</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CoreDepartmant - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_TestLayout.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" rel="stylesheet" />
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

<body>

	<!-- Sidebar -->
	<div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
		<h3 class="w3-bar-item">Menu</h3>
		<a href="/Depart/Index/" class="w3-bar-item w3-button">Departments</a>
		<a href="/Personel/Index/" class="w3-bar-item w3-button">Personels</a>
		<a href="#" class="w3-bar-item w3-button">About Us</a>
		<a href="#" class="w3-bar-item w3-button">Exit</a>
	</div>

	<!-- Page Content -->
	<div style="margin-left:15%">

		<div class="w3-container w3-teal">
			<h1>Asp.Net Core Mvc Project Development</h1>
		</div>


		<div class="w3-container">
			@RenderBody()
		</div>

	</div>

</body>
</html>